#!/bin/bash

# build nvidia modules using dkms
# TODO replace with a systemd service file

set -e
set -x

HOST=x86_64-pc-linux-gnu
VERSION=$(cave print-best-version nvidia-drivers | cut -d '-' -f4 | cut -d ':' -f1)

# create expected source directory
cd /usr/src
sudo ln -s nvidia-drivers nvidia-${VERSION}

# add shims for build tools
cd /usr/bin
sudo ln -s {${HOST}-,}gcc
sudo ln -s {${HOST}-,}ld
sudo ln -s gcc cc

sudo dkms remove nvidia/${VERSION} --all
sudo dkms add nvidia/${VERSION}
sudo dkms autoinstall

# remove shims
sudo rm gcc
sudo rm cc
sudo rm ld

# remove linked source directory
cd /usr/src
sudo rm nvidia-${VERSION}
