#!/bin/bash

# updates the rust nightly channel

set -ex

update_toolchain() {
  local tf=$(mktemp)
  rustup update nightly 2>&1 | tee $tf

  if cat $tf | grep -q 'nightly.*unchanged'; then
    rm $tf
    exit 0
  fi

  rm $tf
}

uninstall() {
  cargo uninstall $1 2>/dev/null || true
}

handles=()
fork_install() {
    if [[ $1 == *"https"* ]]; then
        nice -n10 cargo install --git $1 &
    else
        nice -n10 cargo install $1 &
    fi
    handles+=( $! )
}

join_installs() {
    local pid
    for pid in "${handles[@]}"; do
        wait $pid
    done
}

# TODO(rust-lang/cargo#2405) use cargo install --update
rebuild_packages() {
  uninstall cargo-check
  fork_install https://github.com/rsolomo/cargo-check

  uninstall cargo-clone
  fork_install cargo-clone

  uninstall cargo-edit
  fork_install cargo-edit

  uninstall cargo-outdated
  fork_install https://github.com/kbknapp/cargo-outdated

  uninstall cargo-watch
  fork_install https://github.com/passcod/cargo-watch

  uninstall mdbook
  fork_install https://github.com/azerupi/mdBook

  uninstall mpd
  fork_install https://github.com/japaric/mpc.rs

  uninstall racer
  fork_install https://github.com/phildawes/racer

  uninstall rustfmt
  fork_install https://github.com/rust-lang-nursery/rustfmt

  uninstall scripts
  fork_install https://github.com/japaric/scripts

  uninstall xargo
  fork_install https://github.com/japaric/xargo

  pushd ~/rust/cargo-clippy
  git pull
  cargo clean
  cargo update
  # note clippy breaks every now and then
  nice -n10 cargo build --release || true
  popd

  join_installs
}

fetch_src() {
  local hash=$(rustc -Vv | grep commit-hash | cut -d' ' -f2)

  if [ -d ~/rust/nightly ]; then
    chmod -R a+w ~/rust/nightly
    rm -r ~/rust/nightly
    mkdir ~/rust/nightly
  fi

  curl -sL https://github.com/rust-lang/rust/archive/$hash.tar.gz | \
      tar -xz -C ~/rust/nightly --strip-components 1

  rm -r ~/rust/nightly/src/test

  chmod -R a-w ~/rust/nightly
}

main() {
  update_toolchain
  rebuild_packages
  fetch_src
}

main
