#!/bin/bash

# updates the rust nightly channel

set -ex

update_toolchain() {
  output=$(rustup update nightly | tee /dev/tty)

  if echo $output | grep -q 'nightly unchanged'; then
    exit 0
  fi
}

uninstall() {
  cargo uninstall $1 2>/dev/null || true
}

handles=()
fork_install() {
    local temp_dir=$(mktemp -d)

    pushd $temp_dir
    if [[ $1 == *"https"* ]]; then
        cargo install --git $1 &
    else
        cargo install $1 &
    fi
    handles+=( $!-$temp_dir )

    popd
}

join_installs() {
    local pid temp_dir

    for handle in "${handles[@]}"; do
        pid=$(echo $handle | cut -d'-' -f1)
        temp_dir=$(echo $handle | cut -d'-' -f2)

        wait $pid
        rm -r $temp_dir
    done
}

# TODO(rust-lang/cargo#2405) use cargo install --update
rebuild_packages() {
  uninstall cargo-check
  fork_install https://github.com/rsolomo/cargo-check

  uninstall cargo-edit
  fork_install cargo-edit

  uninstall cargo-outdated
  fork_install https://github.com/kbknapp/cargo-outdated

  uninstall cargo-watch
  fork_install https://github.com/passcod/cargo-watch

  uninstall dybuk
  fork_install https://github.com/Ticki/dybuk

  uninstall mdbook
  fork_install https://github.com/azerupi/mdBook

  uninstall mpd
  fork_install https://github.com/japaric/mpc.rs

  uninstall racer
  fork_install https://github.com/phildawes/racer

  uninstall rustfmt
  fork_install https://github.com/rust-lang-nursery/rustfmt

  uninstall scripts
  fork_install https://github.com/japaric/scripts

  uninstall xargo
  fork_install https://github.com/japaric/xargo

  pushd ~/rust/cargo-clippy
  git pull
  cargo clean
  cargo update
  cargo build --release
  popd

  join_installs
}

fetch_src() {
  local date=$(curl -sL https://static.rust-lang.org/dist/channel-rust-nightly-date.txt)

  if [ -d ~/rust/nightly ]; then
    chmod -R a+w ~/rust/nightly
    rm -r ~/rust/nightly
    mkdir ~/rust/nightly
  fi

  curl -sL https://static.rust-lang.org/dist/$date/rustc-nightly-src.tar.gz | \
    tar xz -C ~/rust/nightly --strip-components 1

  chmod -R a-w ~/rust/nightly
}

main() {
  update_toolchain
  rebuild_packages
  fetch_src
}

main
