#!/bin/bash

# updates the rust nightly channel

set -x

# update toolchain
output=$(multirust update nightly | tee /dev/tty)

if echo $output | grep -q 'is already up to date'; then
  exit 0
fi

# update cargo packages
cargo uninstall cargo-check
cargo install --git https://github.com/rsolomo/cargo-check

cargo uninstall cargo-edit
cargo install --git https://github.com/killercup/cargo-edit

cargo uninstall cargo-outdated
cargo install --git https://github.com/kbknapp/cargo-outdated

cargo uninstall cargo-watch
cargo install --git https://github.com/passcod/cargo-watch

cargo uninstall dybuk
cargo install --git https://github.com/Ticki/dybuk

cargo uninstall mdbook
cargo install --git https://github.com/azerupi/mdBook

cargo uninstall mpd
cargo install --path ~/rust/mpc

cargo uninstall rustfmt
cargo install --git https://github.com/rust-lang-nursery/rustfmt

cargo uninstall scripts
cargo install --path ~/rust/scripts

set -e

# fetch rust source
if [ -d ~/rust/nightly ]; then
  chmod -R a+w ~/rust/nightly
  rm -r ~/rust/nightly
  mkdir ~/rust/nightly
fi
curl -sL https://static.rust-lang.org/dist/rust-nightly-src.tar.gz | \
  tar xz -C ~/rust/nightly --strip-components 1
chmod -R a-w ~/rust/nightly
